### ISSUE TITLE
function `var`  break highlight when adding fallback value

### ISSUE THREAD

**Issue by Yuuki-Yuuna** [radium-v/Better-Less#28]
I'm using Default Dark Modern Themes in Visual Studio

---

highlight is broken by `var` because of adding fallback value.

<img width="420" alt="image" src="https://github.com/radium-v/Better-Less/assets/108787407/f5eace40-0ce6-4079-8d51-bc0c5c1862de">

**Comment by MarekOCLC** [comment]
This may be the same issue or is related: my highlighting breaks when using a variable within an rgba() color

<img width="412" alt="Screenshot 2024-02-19 at 12 02 16 PM" src="https://github.com/radium-v/Better-Less/assets/102601087/84f0470c-cfc2-4331-a0d2-01a0028ffc2d">

```less
:root {
  --off-black: 0,10,20;
  --text-primary: rgba(var(--off-black),0.8);
  --text-secondary: rgba(var(--off-black),0.7);
}
:root {
  color: rgba(var(--off-black),0.8);
  background: #fff;
}
```
